import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from 'next-auth/react';
import { TanstackProvider } from '@/providers/tanstackProvider';
import { auth } from '@/auth';
import ToasterProvider from '@/providers/toasterProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	const session = await auth();
	return (
		<html lang="ru">
			<body className={inter.className}>
				<SessionProvider session={session}>
					<TanstackProvider>
						<ToasterProvider />
						{children}
					</TanstackProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
